sources:
  - generated/StackSansNotch.glyphspackage
familyName: Stack Sans Notch
outputDir: "../fonts/Notch"
cleanUp: true
stat:
  StackSansNotch[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
